version: "3.9"

services:
  docx-template:
    image: ghcr.io/molodsom/docx-generator:latest
    restart: always
    environment:
      - DB_URL=postgresql://testusr:testpasswd@db:5432/testusr
    volumes:
      - ./result:/result
      - ./upload:/upload
    ports:
      - "80:80"
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: testusr
      POSTGRES_PASSWORD: testpasswd